[env]
SHELL = "/usr/bin/fish"

# behavior
    [general]
    live_config_reload = true

    [scrolling]
    history = 1000
    multiplier = 3

    [selection]
    save_to_clipboard = false
    semantic_escape_chars = ",│`|:\"' ()[]{}<>"

# ui

    [cursor]
    style = "Block"
    unfocused_hollow = true

    [mouse]
    hide_when_typing = true

    [bell]
    animation = "EaseOutExpo"

    [window]
    decorations = "none"
    dynamic_title = true

    [window.dimensions]
    columns = 0
    lines = 0

    [window.padding]
    x = 0
    y = 0
