#!/usr/bin/env sh

# export UBSAN_OPTIONS=print_stacktrace=1
# export ASAN_OPTIONS=log_path=/tmp/nvim_asan,handle_abort=1,handle_sigill=1
export NVIM_PROFILES="${nvim_profiles:-coding}"
exec nvim --luamod-dev "$@"
