
basiclibs := python-attrs python-psutil python-requests
devtools := python-isort python-black
asynclibs := python-trio python-httpx python-hyperlink

install:
	sudo pacman -Sy --needed ${basiclibs} ${devtools}

