---generated by scripts/geni.lua at 2025-11-20
---@diagnostic disable: undefined-field
--stylua: ignore start

local M = { x = {} }

local api = vim.api

M.buf_attach               = api.nvim_buf_attach
M.buf_call                 = api.nvim_buf_call
M.buf_clear_namespace      = api.nvim_buf_clear_namespace
M.buf_create_user_command  = api.nvim_buf_create_user_command
M.buf_del_extmark          = api.nvim_buf_del_extmark
M.buf_del_keymap           = api.nvim_buf_del_keymap
M.buf_del_mark             = api.nvim_buf_del_mark
M.buf_del_user_command     = api.nvim_buf_del_user_command
M.buf_del_var              = api.nvim_buf_del_var
M.buf_delete               = api.nvim_buf_delete
M.buf_get_changedtick      = api.nvim_buf_get_changedtick
M.buf_get_commands         = api.nvim_buf_get_commands
M.buf_get_extmark_by_id    = api.nvim_buf_get_extmark_by_id
M.buf_get_extmarks         = api.nvim_buf_get_extmarks
M.buf_get_keymap           = api.nvim_buf_get_keymap
M.buf_get_lines            = api.nvim_buf_get_lines
M.buf_get_mark             = api.nvim_buf_get_mark
M.buf_get_name             = api.nvim_buf_get_name
M.buf_get_offset           = api.nvim_buf_get_offset
M.buf_get_text             = api.nvim_buf_get_text
M.buf_get_var              = api.nvim_buf_get_var
M.buf_is_loaded            = api.nvim_buf_is_loaded
M.buf_is_valid             = api.nvim_buf_is_valid
M.buf_line_count           = api.nvim_buf_line_count
M.buf_set_extmark          = api.nvim_buf_set_extmark
M.buf_set_keymap           = api.nvim_buf_set_keymap
M.buf_set_lines            = api.nvim_buf_set_lines
M.buf_set_mark             = api.nvim_buf_set_mark
M.buf_set_name             = api.nvim_buf_set_name
M.buf_set_text             = api.nvim_buf_set_text
M.buf_set_var              = api.nvim_buf_set_var

M.call_dict_function       = api.nvim_call_dict_function
M.call_function            = api.nvim_call_function

M.chan_send                = api.nvim_chan_send

M.clear_autocmds           = api.nvim_clear_autocmds

M.cmd                      = api.nvim_cmd

M.command                  = api.nvim_command

M.create_augroup           = api.nvim_create_augroup
M.create_autocmd           = api.nvim_create_autocmd
M.create_buf               = api.nvim_create_buf
M.create_namespace         = api.nvim_create_namespace
M.create_user_command      = api.nvim_create_user_command

M.del_augroup_by_id        = api.nvim_del_augroup_by_id
M.del_augroup_by_name      = api.nvim_del_augroup_by_name
M.del_autocmd              = api.nvim_del_autocmd
M.del_current_line         = api.nvim_del_current_line
M.del_keymap               = api.nvim_del_keymap
M.del_mark                 = api.nvim_del_mark
M.del_user_command         = api.nvim_del_user_command
M.del_var                  = api.nvim_del_var

M.echo                     = api.nvim_echo

M.eval                     = api.nvim_eval
M.eval_statusline          = api.nvim_eval_statusline

M.exec_autocmds            = api.nvim_exec_autocmds

M.exec2                    = api.nvim_exec2

M.feedkeys                 = api.nvim_feedkeys

M.get_all_options_info     = api.nvim_get_all_options_info
M.get_autocmds             = api.nvim_get_autocmds
M.get_chan_info            = api.nvim_get_chan_info
M.get_color_by_name        = api.nvim_get_color_by_name
M.get_color_map            = api.nvim_get_color_map
M.get_commands             = api.nvim_get_commands
M.get_context              = api.nvim_get_context
M.get_current_buf          = api.nvim_get_current_buf
M.get_current_line         = api.nvim_get_current_line
M.get_current_tabpage      = api.nvim_get_current_tabpage
M.get_current_win          = api.nvim_get_current_win
M.get_hl                   = api.nvim_get_hl
M.get_hl_id_by_name        = api.nvim_get_hl_id_by_name
M.get_hl_ns                = api.nvim_get_hl_ns
M.get_keymap               = api.nvim_get_keymap
M.get_mark                 = api.nvim_get_mark
M.get_mode                 = api.nvim_get_mode
M.get_namespaces           = api.nvim_get_namespaces
M.get_option_info2         = api.nvim_get_option_info2
M.get_option_value         = api.nvim_get_option_value
M.get_proc                 = api.nvim_get_proc
M.get_proc_children        = api.nvim_get_proc_children
M.get_runtime_file         = api.nvim_get_runtime_file
M.get_var                  = api.nvim_get_var
M.get_vvar                 = api.nvim_get_vvar

M.input                    = api.nvim_input
M.input_mouse              = api.nvim_input_mouse

M.list_bufs                = api.nvim_list_bufs
M.list_chans               = api.nvim_list_chans
M.list_runtime_paths       = api.nvim_list_runtime_paths
M.list_tabpages            = api.nvim_list_tabpages
M.list_uis                 = api.nvim_list_uis
M.list_wins                = api.nvim_list_wins

M.load_context             = api.nvim_load_context

M.open_term                = api.nvim_open_term
M.open_win                 = api.nvim_open_win

M.parse_cmd                = api.nvim_parse_cmd
M.parse_expression         = api.nvim_parse_expression

M.paste                    = api.nvim_paste

M.put                      = api.nvim_put

M.replace_termcodes        = api.nvim_replace_termcodes

M.select_popupmenu_item    = api.nvim_select_popupmenu_item

M.set_current_buf          = api.nvim_set_current_buf
M.set_current_dir          = api.nvim_set_current_dir
M.set_current_line         = api.nvim_set_current_line
M.set_current_tabpage      = api.nvim_set_current_tabpage
M.set_current_win          = api.nvim_set_current_win
M.set_decoration_provider  = api.nvim_set_decoration_provider
M.set_hl                   = api.nvim_set_hl
M.set_hl_ns                = api.nvim_set_hl_ns
M.set_hl_ns_fast           = api.nvim_set_hl_ns_fast
M.set_keymap               = api.nvim_set_keymap
M.set_option_value         = api.nvim_set_option_value
M.set_var                  = api.nvim_set_var
M.set_vvar                 = api.nvim_set_vvar

M.strwidth                 = api.nvim_strwidth

M.tabpage_del_var          = api.nvim_tabpage_del_var
M.tabpage_get_number       = api.nvim_tabpage_get_number
M.tabpage_get_var          = api.nvim_tabpage_get_var
M.tabpage_get_win          = api.nvim_tabpage_get_win
M.tabpage_is_valid         = api.nvim_tabpage_is_valid
M.tabpage_list_wins        = api.nvim_tabpage_list_wins
M.tabpage_set_var          = api.nvim_tabpage_set_var
M.tabpage_set_win          = api.nvim_tabpage_set_win

M.win_call                 = api.nvim_win_call
M.win_close                = api.nvim_win_close
M.win_del_var              = api.nvim_win_del_var
M.win_get_buf              = api.nvim_win_get_buf
M.win_get_config           = api.nvim_win_get_config
M.win_get_cursor           = api.nvim_win_get_cursor
M.win_get_height           = api.nvim_win_get_height
M.win_get_number           = api.nvim_win_get_number
M.win_get_position         = api.nvim_win_get_position
M.win_get_tabpage          = api.nvim_win_get_tabpage
M.win_get_var              = api.nvim_win_get_var
M.win_get_width            = api.nvim_win_get_width
M.win_hide                 = api.nvim_win_hide
M.win_is_valid             = api.nvim_win_is_valid
M.win_set_buf              = api.nvim_win_set_buf
M.win_set_config           = api.nvim_win_set_config
M.win_set_cursor           = api.nvim_win_set_cursor
M.win_set_height           = api.nvim_win_set_height
M.win_set_hl_ns            = api.nvim_win_set_hl_ns
M.win_set_var              = api.nvim_win_set_var
M.win_set_width            = api.nvim_win_set_width
M.win_text_height          = api.nvim_win_text_height

M.x.buf_debug_extmarks     = api.nvim__buf_debug_extmarks
M.x.buf_stats              = api.nvim__buf_stats
M.x.complete_set           = api.nvim__complete_set
M.x.get_lib_dir            = api.nvim__get_lib_dir
M.x.get_runtime            = api.nvim__get_runtime
M.x.id                     = api.nvim__id
M.x.id_array               = api.nvim__id_array
M.x.id_dict                = api.nvim__id_dict
M.x.id_float               = api.nvim__id_float
M.x.inspect_cell           = api.nvim__inspect_cell
M.x.invalidate_glyph_cache = api.nvim__invalidate_glyph_cache
M.x.ns_get                 = api.nvim__ns_get
M.x.ns_set                 = api.nvim__ns_set
M.x.redraw                 = api.nvim__redraw
M.x.runtime_inspect        = api.nvim__runtime_inspect
M.x.screenshot             = api.nvim__screenshot
M.x.stats                  = api.nvim__stats
M.x.unpack                 = api.nvim__unpack

return M
--stylua: ignore end
