#!/usr/bin/env sh

#
# read manpage in nvim
#

# for `man ascii | :h`
if [ -p /proc/self/fd/0 ]; then
    # since stdin is a pipe,
    # we copy self.stdin to nvim via exec
    exec ni +"Man!"
fi

# for `:h 7 ascii`
if [ $# -eq 1 ]; then
    exec ni +"edit man://$1"
fi

if [ $# -eq 2 ]; then
    exec ni +"edit man://$2($1)"
fi

>&2 echo "unexpected arg number"
exit 1
