#!/usr/bin/env python3

import os
import shutil
import sys


def main():
    if len(sys.argv) < 2:
        raise SystemExit("requires more args")

    if shutil.which(sys.argv[1]) is None:
        os.execvp("tmux", ["tmux", "splitw", "-h", "vi", *sys.argv[1:]])
    else:
        os.execvp("tmux", ["tmux", "splitw", "-h", *sys.argv[1:]])


if __name__ == "__main__":
    main()
