#!/usr/bin/env python3

"""
see: https://docs.github.com/en/rest?apiVersion=2022-11-28
"""


import subprocess
from argparse import ArgumentParser

import requests


class facts:
    _token = ""

    apiver = "2022-11-28"

    @classmethod
    @property
    def token(cls):
        if cls._token == "":
            cp = subprocess.run(["pass", "github/accesstoken-cli"], check=True, stdout=subprocess.PIPE)
            stdout = cp.stdout.decode()
            assert stdout.endswith("\n")
            cls._token = stdout[:-1]

        return cls._token


def parse_args():
    par = ArgumentParser()
    subpars = par.add_subparsers(dest="op", required=True)
    loc = subpars.add_parser("loc")
    loc.add_argument("owner", type=str)
    loc.add_argument("repo", type=str)
    return par.parse_args()


def main():
    args = parse_args()

    match args.op:
        case "loc":
            # doc: https://docs.github.com/en/rest/repos/repos?apiVersion=2022-11-28#list-repository-languages
            resp = requests.get(
                "https://api.github.com/repos/{}/{}/languages".format(args.owner, args.repo),
                headers={"Accept": "application/vnd.github+json", "Authorization": "Bear {}".format(facts.token), "X-GitHub-Api-Version": facts.apiver},
            )
            print(resp.content)
            if not resp.ok:
                raise SystemExit(1)
        case _:
            raise RuntimeError("unreachable")


if __name__ == "__main__":
    main()
