#!/usr/bin/env sh

#
# inspired from i3-sensible-terminal
#

# shellcheck disable=SC2153
for browser in "$BROWSER" vivaldi-stable firefox chromium; do
    if command -v "$browser" > /dev/null 2>&1; then
        exec "$browser" "$@"
    fi
done

i3-nagbar -m 'i3-sensible-browser could not find a browser. Please install one.'
