#!/bin/sh

export SHELL=/usr/bin/fish
export BGMODE=light
export COLORFGBG='0;15'

# exec /usr/bin/ghostty \
#     --config-file=$HOME/.config/ghostty/light \
#     "$@"

exec /usr/bin/alacritty "$@"
