#!/usr/bin/env sh

# W\*H[+-]X[+-]Y
# which is relatived to
# * screen size
# * position
# * +-n
# * n%

geometry="50%x10%-1%-5%"

/usr/bin/screenkey \
    --font-size large \
    --key-mode raw \
    --font "Monego" \
    --opacity 0.5 \
    --position fixed \
    --geometry "$geometry"
