#!/usr/bin/env python3

import os
import subprocess
from argparse import ArgumentParser

opkey = {"pause": "F1", "unpause": "F2", "mute": "F3", "unmute": "F4"}


def parse_args():
    parser = ArgumentParser()
    parser.add_argument("op", choices=opkey.keys())
    parser.add_argument("--all-desktops", "-a", action="store_true")

    return parser.parse_args()


def main():
    args = parse_args()

    cmd = ["xdotool", "search"]

    if not args.all_desktops:
        cp = subprocess.run(("xdotool", "get_desktop"), check=True, capture_output=True)
        desktop = cp.stdout.rstrip(b"\n").decode()
        cmd.extend(("--desktop", desktop))

    cmd.extend(("--class", "mpv"))
    cmd.extend(("key", "--window", "%@"))

    try:
        key = opkey[args.op]
    except KeyError:
        raise RuntimeError("unknown op")
    else:
        cmd.append(key)

    os.execvp(cmd[0], cmd)


if __name__ == "__main__":
    main()

# vim: ft=python
