#!/usr/bin/env python3

import subprocess
from argparse import ArgumentParser


class Facts:
    dev = "wlan0"
    wifi = "squidward_5g"


def parse_args():
    par = ArgumentParser()
    subpars = par.add_subparsers(dest="op")
    subpars.add_parser("on")
    subpars.add_parser("off")
    subpars.add_parser("status", aliases=("show",))
    return par.parse_args()


def main():
    args = parse_args()
    match args.op:
        case "on":
            subprocess.run(["iwctl", "station", Facts.dev, "connect", Facts.wifi], check=True)
        case "off":
            subprocess.run(["iwctl", "station", Facts.dev, "disconnect"], check=True)
        case None | "status" | "show":
            subprocess.run(["iwctl", "station", Facts.dev, "show"], check=True)
        case _:
            raise RuntimeError("unreachable")


if __name__ == "__main__":
    main()

# vim: ft=python :
